import { CalendarEvent } from "./types";

export const sampleEvents: CalendarEvent[] = [
  {
    id: "1",
    title: "Встреча команды",
    description: "Еженедельное собрание команды",
    startDate: new Date(2024, 11, 15, 9, 0), // 15 декабря 2024, 9:00
    endDate: new Date(2024, 11, 15, 10, 0),
    startTime: "09:00",
    endTime: "10:00",
    allDay: false,
    category: "meeting",
    color: "#33b679",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    title: "Дедлайн проекта",
    description: "Завершить фронтенд разработку",
    startDate: new Date(2024, 11, 20),
    endDate: new Date(2024, 11, 20),
    allDay: true,
    category: "work",
    color: "#7986cb",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3",
    title: "Визит к врачу",
    description: "Ежегодный осмотр",
    startDate: new Date(2024, 11, 18, 14, 30),
    endDate: new Date(2024, 11, 18, 15, 30),
    startTime: "14:30",
    endTime: "15:30",
    allDay: false,
    category: "personal",
    color: "#039be5",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "4",
    title: "Купить продукты",
    description: "Еженедельные покупки",
    startDate: new Date(2024, 11, 16, 18, 0),
    endDate: new Date(2024, 11, 16, 19, 0),
    startTime: "18:00",
    endTime: "19:00",
    allDay: false,
    category: "reminder",
    color: "#f6bf26",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "5",
    title: "День рождения мамы",
    description: "Не забыть поздравить!",
    startDate: new Date(2024, 11, 22),
    endDate: new Date(2024, 11, 22),
    allDay: true,
    category: "personal",
    color: "#039be5",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "6",
    title: "Презентация Q4",
    description: "Отчет по результатам квартала",
    startDate: new Date(2024, 11, 19, 15, 0),
    endDate: new Date(2024, 11, 19, 16, 30),
    startTime: "15:00",
    endTime: "16:30",
    allDay: false,
    category: "work",
    color: "#7986cb",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
