import { CalendarEvent } from "./types";

export const sampleEvents: CalendarEvent[] = [
  {
    id: "1",
    title: "Team Meeting",
    description: "Weekly team standup meeting",
    startDate: new Date(2024, 11, 15, 9, 0), // December 15, 2024, 9:00 AM
    endDate: new Date(2024, 11, 15, 10, 0),
    startTime: "09:00",
    endTime: "10:00",
    allDay: false,
    category: "meeting",
    color: "#8b5cf6",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    title: "Project Deadline",
    description: "Complete frontend implementation",
    startDate: new Date(2024, 11, 20),
    endDate: new Date(2024, 11, 20),
    allDay: true,
    category: "work",
    color: "#3b82f6",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3",
    title: "Doctor Appointment",
    description: "Annual checkup",
    startDate: new Date(2024, 11, 18, 14, 30),
    endDate: new Date(2024, 11, 18, 15, 30),
    startTime: "14:30",
    endTime: "15:30",
    allDay: false,
    category: "personal",
    color: "#10b981",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "4",
    title: "Buy groceries",
    description: "Weekly shopping",
    startDate: new Date(2024, 11, 16, 18, 0),
    endDate: new Date(2024, 11, 16, 19, 0),
    startTime: "18:00",
    endTime: "19:00",
    allDay: false,
    category: "reminder",
    color: "#f59e0b",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
